do

  local function run(msg, matches)
    if not util.isChatMsg(msg) and not util.isPrivileged(user_id, chat_id) then return end

    local chat_id, user_id, _, _ = util.extractIds(msg)
    local phash = 'pin' .. chat_id
    local pin_id = db:get(phash)

    if matches[2] then
      if pin_id then --try to edit the old message
        td.editMessageText(chat_id, pin_id, nil, matches[2], 1, 'HTML', function(a, d)
          if d.ID == "Error" then
            local text = _msg("The old message generated with <code>!pin</code> does not exist anymore, so I can't edit it. This is the new message that can be now pinned")
            sendText(chat_id, a.msg_id, text)
            sendText(chat_id, 0, a.message)
          else
            sendText(chat_id, pin_id, _msg("Message edited. Check it here."))
          end
        end, {msg_id = msg.id_, message = matches[2]})
      else
        local text = _msg('No message has been pinned for %s. Reply these message with <code>!pin</code> to pin it.'):format(db:get('title' .. chat_id))
        sendText(chat_id, msg.id_, text)
        sendText(chat_id, 0, matches[2])
      end
    else
      if util.isReply(msg) then
        if util.isSuperGroup(chat_id) then
          td.pinChannelMessage(chat_id, msg.reply_to_message_id_, 0)
        end
        db:set(phash, msg.reply_to_message_id_)
        local text = _msg('This message is now pinned. Use <code>!pin [new text]</code> to edit it without having to send it again')
        sendText(chat_id, msg.reply_to_message_id_, text)
      else
        if pin_id then
          if matches[1] == 'unpin' then
            db:del(phash)
            td.unpinChannelMessage(chat_id)
            -- Deleting message resulted in ugly deleted message chain
            --td.deleteMessages(chat_id, {[0] = pin_id})
            return sendText(chat_id, msg.id_, _msg('Pinned message has been unpinned.'))
          else
            td.getMessage(chat_id, pin_id, function(a, d)
              if d.ID == "Error" then
                local text = _msg("The pinned message does not exist anymore.")
                sendText(a.chat_id, a.msg_id, text)
              else
                local text = _msg('Last message generated by <code>!pin</code> 👆')
                sendText(a.chat_id, a.pin_id, text)
              end
            end, {chat_id = chat_id, msg_id = msg.id_, pin_id = pin_id})
          end
        else
          local text = _msg('No message has been pinned for %s. Reply a message with <code>!pin</code> to pin it.'):format(db:get('title' .. chat_id))
          sendText(chat_id, msg.id_, text)
        end
      end
    end
  end

--------------------------------------------------------------------------------

  return {
    description = _msg('Pin a message.'),
    usage = {
      moderator = {
        '<code>!pin</code>',
        _msg('Pin a replied message.'),
        '',
        '<code>!pin [text]</code>',
        _msg('Edit an existing pinned message if exist.'),
        '',
      },
      user = {
        '<code>!pin</code>',
        _msg('Show the pinned message.'),
        '',
      },
    },
    patterns = {
      _config.cmd  ..  '(pin)$',
      _config.cmd  ..  '(pin) (.*)$',
      _config.cmd  ..  '(unpin)$',
    },
    run = run
  }

end
